FROM golang:1.22.4 as builder
COPY go.mod go.sum /go/src/github.com/go-game-dev/tm_http/
WORKDIR /go/src/github.com/go-game-dev/tm_http/
RUN go mod download
COPY . /go/src/github.com/go-game-dev/tm_http/
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o build/tm_http github.com/go-game-dev/tm_http

FROM alpine:latest
RUN apk add --no-cache ca-certificates && update-ca-certificates
COPY --from=builder /go/src/github.com/go-game-dev/tm_http/build/tm_http /usr/bin/tm_http
EXPOSE 8080 8080
ENTRYPOINT ["/usr/bin/tm_http"]